name: "New Word"

on:
  issues:
    types: [opened]

jobs:
  NewWord:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.body, '不要更改這裡的內容，請直接更改標題並按下`Submit new issue`!')
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      
    - name: 增加文字
      env:
        REPOSITORY: ${{ github.repository }}
        EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
      run: |
            sh word.sh "${{ github.event.issue.title }}" "${{ github.event.issue.user.login }}"
            echo ${{ secrets.GITHUB_TOKEN }} > token.txt
            gh auth login --with-token < token.txt
            echo supersecret > token.txt
            rm -r token.txt
            git config --local user.email "littlecow.moomoomoo@gmail.com"
            git config --local user.name "LittleCow-Bot"
            git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git  add .
            git commit -m "增加@${{ github.event.issue.user.login }}的文字：${{ github.event.issue.title }}"
            git push -u
            gh issue close https://github.com/charlie-moomoo/textboard/issues/${{ github.event.issue.number }}
